# Generated by Django 3.1.7 on 2021-03-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_expensecategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysummary',
            name='month',
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.expensecategories'),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
