# Generated by Django 3.1.7 on 2021-03-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_auto_20210313_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategories',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.expensecategories', to_field='category'),
        ),
    ]
