# Generated by Django 3.1.7 on 2021-03-13 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_auto_20210313_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
