# Generated by Django 3.1.7 on 2021-03-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_monthlysummary_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysummary',
            old_name='date',
            new_name='expense_date',
        ),
    ]
