# Generated by Django 3.1.7 on 2021-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_auto_20210313_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='expense_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
