# Generated by Django 3.1.7 on 2021-03-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_remove_monthlysummary_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='expense_date',
            field=models.DateField(null=True),
        ),
    ]
