# Generated by Django 3.1.7 on 2021-03-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_auto_20210316_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.expensecategories'),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
