# Generated by Django 3.1.7 on 2021-03-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_auto_20210320_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.expensecategories', to_field='category'),
        ),
    ]
